### ISSUE TITLE
Analysis plan feedback

### ISSUE THREAD

**Issue by ksedivyhaley** [UBC-MDS/DSCI_522_group-314#20]
Overall your proposal has a good level of detail, though some aspects need to be specified (for example, what split are you using for training and testing data, and how many folds are you using for your cross-validation?). Also:

> Other models such as Logistic Regression, K-nearest neighborhood and Support Vector Machine will also be explored. 

Recommend picking and sticking with one model unless there's a compelling reason to consider multiple – in which case, explain how you will pick between the models as your analysis progresses.

> The many outliers in the boxplot indicate heavy-tail distribution for many of the feature’s relationships such as Limit balance and Sex, Education and Marriage which is important to consider during the subsequent data analysis.

How would this consideration affect your analysis?

I am also checking with Firas and Tiffany regarding some technical details of your analysis plan with which I am unfamiliar, to ensure the analysis is correct as proposed.

**Comment by ksedivyhaley** [comment]
> I am also checking with Firas and Tiffany regarding some technical details of your analysis plan with which I am unfamiliar, to ensure the analysis is correct as proposed.

In case you were worried - all good!

**Comment by zoepan00** [comment]
.
