### ISSUE TITLE
Submission Link issues

### ISSUE THREAD

**Issue by ksedivyhaley** [UBC-MDS/DSCI_522_group-314#21]
- All your individual submissions should link to https://github.com/UBC-MDS/DSCI_522_group-314/tree/v0.2
  - Linking in the README is better than none but read instructions carefully (and test your link in the README - it's broken)
- Elliot has no release link at all, just main repo
- Zhengyang needs link to team contract in submission

**Comment by zoepan00** [comment]
.

**Comment by zoepan00** [comment]
Thank you Kate!

**Comment by zoepan00** [comment]
.
