### ISSUE TITLE
Minor feedback

### ISSUE THREAD

**Issue by ksedivyhaley** [UBC-MDS/DSCI_522_group-314#23]
**EDA**

- Warning: best practice to split test data as early as possible - before viewing df.tail().
- "So we might need to drop some columns when fitting the model or choose the model that won't be affected by the collinearity of predictors." - good observation! I'd put it in the conclusions (your conclusion states more vaguely that you'll "consider" it but it's worth being specific).
- Do you know why there are so many 0s in the repayment status?

**Other**

- Proposal should also suggest likely tables/figures for end report
- README in data folder with data citation is nice! It's good to have the citation in the main README as well, and **you should [cite also the repository](https://archive.ics.uci.edu/ml/citation_policy.html).**

**Comment by ksedivyhaley** [comment]
Clarification: I think I mentioned this in class, but the only one of these items that I'd consider a priority to fix is the data citation. If you address the others, great, but focus on the download script #22 and making sure you clearly communicate your analysis in the final report (keeping in mind the questions in #20 ).

**Comment by zoepan00** [comment]
Thank you Kate!
