### ISSUE TITLE
Script improvements - tests, documentations

### ISSUE THREAD

**Issue by ksedivyhaley** [UBC-MDS/DSCI_522_group-314#35]
- Download script still needs a test (see #22)
  - Would be helpful to include default URL in the documentation
- Wrangling script could use more code comments
- EDA needs test, documentation of your individual graphing functions.
- Analysis needs test, documentation of individual functions.

Also: data split should occur in the wrangling script, rather than doing it in both of EDA and analysis.

**Comment by ribner** [comment]
I will add wrangling comments and test. Also need to add test to analysis.

**Comment by dataubc** [comment]
Will do the documentation of individual functions for Analysis
