### ISSUE TITLE
Visualization feedback

### ISSUE THREAD

**Issue by ksedivyhaley** [UBC-MDS/DSCI_522_group-314#36]
Most figures are good in overall construction, but need to be presented in a clearer way.

- Make sure all figure labels are polished (no underscores, correctly capitalized)
- Label Tables "Table #" and number separately from figures.
- Figure 1 is unnecessary
- Figure 2 display fewer significant figures, and use nicer column labels
- Figure 3 is highly effective - to improve, use nicer labels and set the diagonal to be a colour other than the highest value.
- Figure 4 isn't very effective. Have you tried a violin plot? Otherwise, cumulative distribution? 
- Arrange Figure 5 next to Figure 6 for easier interpretation - and label "Default"/"No default" as opposed to 0/1
- Combine your evaluation_matrix and evaluation_matrix_base tables, and use informative column names

**Comment by ribner** [comment]
Label the confusion matrix as specified in lecture 1. Rename results df left column as "evaluation parameter". Combine two results df into one.

**Comment by dataubc** [comment]
Arranged Figure 5 next to Figure 6 for easier interpretation
