### ISSUE TITLE
Report feedback

### ISSUE THREAD

**Issue by ksedivyhaley** [UBC-MDS/DSCI_522_group-314#37]
- Good introduction of question, data
- **[Important]** Necessary to critique your analysis and give a statement of future directions
- **[Important]** Figure 7 needs more explanation - how are you assessing "pretty good"?
- You mention "Past monthly repayment status in September 2005" twice - should this be two different months?
  - Also, given the date of the data set, can we generalize this eg to X number of months after credit is extended/before end of payment plan?
- Cite at least one external source other than data
- **[Important]** This section is unclear, and needs re-writing. Consider false positive / false negative trade-offs.

> We can see that the best model which uses 7 features tends to correctly predict the customer that defaulted out-performing the base-case model which uses all the features. This is critically important in risk management. We can see that 4600 predictions were made that correctly classified a non-default as a non-default. This is about 600 cases better than the base-case model. There was also 1200 predictions that were made that incorrectly classified a non-default as a default, actually about 700 cases worse than the best-case model.On the other hand the model was able to predict 940 cases of defaulted customers that actually defaulted which is about 160 cases worse than base-case model. The best-case model was also able to produce 720 predictions were made that incorrectly classified a defaulted customers as a defaulted customers.

**Comment by dataubc** [comment]
[Important] This section is unclear, and needs re-writing. Consider false positive / false negative trade-offs.
Rewrote the section
